import esbuild from "esbuild";
import process from "node:process";
import fs from "node:fs";
import path from "node:path";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Source: https://github.com/rokokol/obsidian-obsictionary
*/`;

const production = process.argv[2] === "production";

/** Files copied to the vault plugin dir after a successful build. */
const artifacts = ["main.js", "manifest.json", "styles.css"];

/**
 * Copy build artifacts into the Obsidian vault plugin folder, if configured.
 * Path comes from OBSIDIAN_PLUGIN_DIR (a local .env or the shell env) so the
 * public repo never hardcodes a machine-specific vault path.
 */
function copyToVault() {
  const target = process.env.OBSIDIAN_PLUGIN_DIR;
  if (!target) return;
  fs.mkdirSync(target, { recursive: true });
  for (const file of artifacts) {
    if (fs.existsSync(file)) {
      fs.copyFileSync(file, path.join(target, file));
    }
  }
  console.log(`[obsictionary] copied artifacts -> ${target}`);
}

const copyPlugin = {
  name: "copy-to-vault",
  setup(build) {
    build.onEnd((result) => {
      if (result.errors.length === 0) copyToVault();
    });
  },
};

// Load OBSIDIAN_PLUGIN_DIR from a local .env if present (dev convenience).
const envFile = path.resolve(".env");
if (fs.existsSync(envFile)) {
  for (const line of fs.readFileSync(envFile, "utf8").split("\n")) {
    const match = /^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/.exec(line);
    if (match && match[1] && !process.env[match[1]]) {
      process.env[match[1]] = match[2].replace(/^["']|["']$/g, "");
    }
  }
}

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  sourcemap: production ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: production,
  plugins: [copyPlugin],
});

if (production) {
  await context.rebuild();
  await context.dispose();
} else {
  await context.watch();
}
